### ISSUE TITLE
Maya 2017 issue

### ISSUE THREAD

**Issue by clementejacques** [robertjoosten/maya-timeline-marker#2]
Hey, I saw you can now buy it on gumroad so I did. 

This time I tried to install it on autodesk maya 2017 and I am getting this error when running the python script.  Cheers!

# Error: ImportError: file /Users/myname/Library/Preferences/Autodesk/maya/2017/prefs/scripts/rjTimelineMarker.py line 28: No module named PySide #

**Comment by robertjoosten** [comment]
I see this is an issue from a while back. Only just seen this my apologies.
Maya 2017 should work. So if you haven't downloaded the repository again already. Im sure you can try again.

```
# import pyside, do qt version check for maya 2017 >
qtVersion = cmds.about(qtVersion=True)
if qtVersion.startswith("4") or type(qtVersion) not in [str, unicode]:
    from PySide.QtGui import *
    from PySide.QtCore import *
    import shiboken
else:
    from PySide2.QtGui import *
    from PySide2.QtCore import *
    from PySide2.QtWidgets import *
    import shiboken2 as shiboken
```

This ensures the right version of PySide is imported.
